image: node:6

stages:
  - build
  - test
  - deploy

check_deps:
  stage: build
  script:
    - npm install --silent
    - npm run check-deps --silent
  allow_failure: true

jest:
  stage: test
  script:
    - npm install --silent
    - npm test -- --coverage

build_image:
  stage: deploy
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  only:
    - tags
