image: registry.asap.dsna.fr/4me/node-yarn:v7.2.0

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

before_script:
  - export no_proxy=docker

variables:
  BUILD_ARGS: "--build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy"

stages:
  - test
  - deploy

jest:
  stage: test
  script:
    - yarn
    - npm test -- --coverage

build_release_image:
  stage: deploy
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build $BUILD_ARGS -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  only:
    - tags

build_image:
  stage: deploy
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build $BUILD_ARGS -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  only:
    - master
